### ISSUE TITLE
Spring Boot 3.0.0 Milestone

### ISSUE THREAD

**Issue by nicolasb29** [ivangfr/graalvm-quarkus-micronaut-springboot#22]
Hi,

Thank you for this awesome repository, very interesting !

Have you tried a milestone version of Spring Boot 3.0.0 to notice a difference of size, start time and response time between 2.7.x and 3.x ?

**Comment by ivangfr** [comment]
Hi @nicolasb29 . Thanks! No, not yet. I will try Spring Boot 3.x just when Spring team releases the final version of it.

**Comment by nicolasb29** [comment]
Hi,

Ok, thanks!

**Comment by ivangfr** [comment]
Hi @nicolasb29 I've upgrade the spring-boot applications to version `3.0.0`. You can see the stats differences between `2.7.4` and `3.0.0` in the [README changes](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/commit/a88de85f0250fffcf89443a1fbae5d5b128e3bbb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

**Comment by nicolasb29** [comment]
Hi, 
Thanks a lot, I’m going to look! You have used a tool like OpenRewrite to migrate?

**Comment by ivangfr** [comment]
No, I didn't use OpenRewrite. In fact, I didn't know the tool. It looks interesting. I will try it to migrate another project I have. Thanks for sharing.
