### ISSUE TITLE
Micronaut 4.x Native Image build Broken ? 

### ISSUE THREAD

**Issue by subash89** [ivangfr/graalvm-quarkus-micronaut-springboot#23]
Hi, @ivangfr 
I tried the micronaut simple api project and able to successfully build a native image with your latest branch, on micronaut 3.9.x. But when I try to update it to 4.x and then try to build I am getting 
**/app/application: /usr/glibc-compat/lib/libc.so.6: version `GLIBC_2.34' not found (required by /app/application)**

Is there a way I can still use jib plugin and get GLIBC issue fixed ?

**Comment by ivangfr** [comment]
Hi @subash89 I haven't tried yet to upgrade to Micronaut 4.

I've seen that you interacted in this issue https://github.com/micronaut-projects/micronaut-core/issues/9664

Have you tried what @sgammon proposed?

**Comment by subash89** [comment]
I am trying to understand how to use that native image build with mvn -Dpackaging=docker-native.    Any idea how to pass a custom built native image to the maven plugin.

**Comment by subash89** [comment]
@ivangfr  is micronaut completely depend on jib to build the image or does it do anything like with some custom plugin. 
Basically does it allows to start off with such custom native image ?

**Comment by ivangfr** [comment]
No, it does not depend on Jib. Maybe, check this https://guides.micronaut.io/latest/micronaut-docker-image-gradle-java.html
