### ISSUE TITLE
Add NonBlocking annotation to Quarkus 

### ISSUE THREAD

**Issue by franz1981** [ivangfr/graalvm-quarkus-micronaut-springboot#25]
As explained in https://medium.com/@nigro.fra/i-suggest-to-add-nonblocking-annotation-to-the-quarkus-end-point-%EF%B8%8F-as-usual-folks-doesnt-know-cf32236e003a for simple non blocking user defined structures, the default ergonomic of Quarkus is still to use the blocking thread pool, while for this use case (which is non blocking amd in-memory), would be better to use the I/O thread, saving resources, CPU and improving throughput.

In order to do that add NonBlocking annotation to the endpoint which is expected to NOT be blocking (ie greetings).

**Comment by franz1981** [comment]
Moreover, I see that quarkus seems to use resteasy (which should be removed), which is NOT what users should use; instead switch to resteasy-reactive, which is, despite what the name suggest, the expected choice for most users, and is NOT just for reactive use cases only. It is internally fully reactive (an implementation detail which users shouldn't be aware really), but it allows to both run blocking and non blocking endpoints (which is the part users should care about, instead).

**Comment by ivangfr** [comment]
Thanks @franz1981 for the suggestion. I've applied the changes.
