### ISSUE TITLE
Use RESTEasy Reactive in Quarkus applications

### ISSUE THREAD

**Issue by geoand** [ivangfr/graalvm-quarkus-micronaut-springboot#26]
For the REST stack, `quarkus-resteasy-reactive` has been the default (and suggested) choice over `quarkus-resteasy`, so I propose the code / numbers / text be updated.

Thanks

**Comment by ivangfr** [comment]
Thanks @geoand for the suggestion. I will apply the changes.

Duplicated of https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/issues/25

**Comment by geoand** [comment]
👌
