### ISSUE TITLE
Stack traces can be in console 

### ISSUE THREAD

**Issue by akondasif** [ivangfr/graalvm-quarkus-micronaut-springboot#3]
Greetings,

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of improper exception handling.

According to CWE, stack traces due to exception handling should not be printed. See https://cwe.mitre.org/

Source: https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/blob/master/book-api/quarkus-book-api/.mvn/wrapper/MavenWrapperDownloader.java

Fix: https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/pull/2

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by ivangfr** [comment]
Hey @akondasif,

Thanks for the code analysis. Btw, I didn't write this `MavenWrapperDownloader.java` file. It came when I generated this project using Quarkus website https://code.quarkus.io/

Maybe, it would be interesting to talk to Quarkus team and propose some security improvement in `MavenWrapperDownloader.java`

Best regards,

**Comment by akondasif** [comment]
@ivangfr 

Thanks for the feedback ... we will move this discussion to the `Quarkus` website
