### ISSUE TITLE
so what is your choice?

### ISSUE THREAD

**Issue by feitian124** [ivangfr/graalvm-quarkus-micronaut-springboot#8]
thank you for this awesome repo. some other compare:
  
## quarkus
1. more popular. start 1 year later but get 2k more star
2. its devrun hot reload.(what is the underlying tech ? other framework seems can not do this without jrebel )
3. plugin system
4. cloud native, all k8s things.

## micronaut
1. better gradle, kotlin support
2. more simplified and unified api
3. compile time data to implement dependency injection; better documents.
4. better traditional micro service support like config center, registry center etc.

personally i prefer micronaut as point 1 and 2, but your test make me hesitate。。

**Comment by ivangfr** [comment]
Hi @feitian124 It's a difficult question. Honestly, I don't have an answer for that right now :) That is why I have created this project. Let's see in the future if I can answer your question. But, until now, I like and enjoy working with all, `Spring Boot`, `Quarkus` and `Micronaut`.

**Comment by feitian124** [comment]
thanks. the same to me
